### ISSUE TITLE
Converted documents gets background colour?

### ISSUE THREAD

**Issue by Hund** [walwe/md2pdf#2] opened 2017-07-09 15:52 UTC
I noticed today that when I convert documents I get a background colour as well. Is this a bug or feature?

![screenshot_2017-07-09_17-47-36](https://user-images.githubusercontent.com/320498/27995463-0562bda4-64cf-11e7-8c1c-bfbc0e06448c.png)

I'm using the version `0.0.3.r0.gac9bce4-1` from AUR.

**Comment by walwe** [comment] 2017-07-10 08:44
This is not the intended behaviour, the background color #f7f7f7 is only used in code blocks.
Unfortunately I cannot reproduce the problem.
Could you please run using ```--keep-html``` and upload the temporary HTML file?

**Comment by Hund** [comment] 2017-07-10 09:51
Sure! https://pastebin.com/tyLesM0j

**Comment by walwe** [comment] 2017-07-10 10:12
I am not sure what is causing the problem as the temporary HTML is fine and should render correct in your browser. This seems to be a problem of wkhtmltopdf.
Are you up-to-date with your versions?
```
> pacman -Q wkhtmltopdf
wkhtmltopdf 0.12.4-1
> pacman -Q qt5-webkit
qt5-webkit 5.212.0alpha2-4
```

**Comment by Hund** [comment] 2017-07-10 10:39
I am. :)

```
wkhtmltopdf 0.12.4-1
qt5-webkit 5.212.0alpha2-4
```

**Comment by walwe** [comment] 2017-07-11 12:45
Please check the resulting PDF when calling wkhtmltopdf manually:
```
wkhtmltopdf test.html test.pdf
```

**Comment by Hund** [comment] 2017-07-11 16:50
Same thing.

**Comment by walwe** [comment] 2017-09-19 11:40
Sorry for the very late reply. 
I fear that this means wkhtmltopdf is not converting the HTML correctly and this needs to be fixed on their side.

**Comment by yourealwaysbe** [comment] 2020-02-03 17:33
I think this is caused by [transparent backgrounds](https://github.com/wkhtmltopdf/wkhtmltopdf/pull/2084) which are a deliberate feature of wkhtmltopdf. This roughly means that the md2pdf background color matches the desktop theme of the user, unless they are somehow able to specify the CSS property "background: white".

Adding the following to the start of the md file works for me, though it's not ideal.

    <style>
        * { background: white }
    </style>

**Comment by walwe** [comment] 2020-02-26 06:29
Thank you @yourealwaysbe for the hint.
I conclude: 
- wkhtml2pdf swapped white and transparent [2084#issuecomment-65717558](https://github.com/wkhtmltopdf/wkhtmltopdf/pull/2084#issuecomment-65717558)
- On windows the default theme background is used [2084#issuecomment-6866174](https://github.com/wkhtmltopdf/wkhtmltopdf/pull/2084#issuecomment-68661742)
- Waiting to be fixed in [2152](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2152)

Not sure how to fix this nicely without using the swapped background definition.

**Comment by amalgame21** [comment] 2022-09-29 17:13
In my case, the background was very dark grey, so the text is almost not visible.
Confirm that the problem is caused by wkhtmltopdf, and the environment variable of the system desktop theme.
Because I use dark theme, so the background become very dark.

Found an answer here.
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4316#issuecomment-643153161

**Comment by amalgame21** [comment] 2022-09-29 17:16
Coming here from the ```zaread``` bash script, which is a good script for ```zathura``` as MSOffice and OpenOffice documents reader, and also md reader, which depends on ```md2pdf```.

In my case, the background was very dark grey, so the text is barely visible.
Confirmed that the problem was caused by ```wkhtmltopdf```, and the environment variable of the system desktop theme.
Because I use dark theme, so the background become very dark.

Found a solution here for ```wkhtmltopdf```.
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4316#issuecomment-643153161

Seems it also work for md2pdf:
```env QT_STYLE_OVERRIDE=fusion md2pdf ...```

**Closed as completed** 2023-06-02 09:11 UTC
